//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestCAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsigCursoRol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsigCursoRol()
        {
            this.Cursos1 = new HashSet<Cursos>();
        }
    
        public int IdAsignacion { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdCurso { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursos> Cursos1 { get; set; }
    }
}
