//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestCAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cursos()
        {
            this.AsigCursoRol = new HashSet<AsigCursoRol>();
            this.CursosMatriculados = new HashSet<CursosMatriculados>();
        }
    
        public int IdCurso { get; set; }
        public string NombreCurso { get; set; }
        public Nullable<int> CodigoCurso { get; set; }
        public Nullable<int> IdModulo { get; set; }
        public Nullable<int> IdAsignacion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsigCursoRol> AsigCursoRol { get; set; }
        public virtual AsigCursoRol AsigCursoRol1 { get; set; }
        public virtual Modulos Modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursosMatriculados> CursosMatriculados { get; set; }
    }
}
