//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestCAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluaciones()
        {
            this.CursosMatriculados = new HashSet<CursosMatriculados>();
        }
    
        public int IdEvaluacion { get; set; }
        public Nullable<decimal> ValorObtenido { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public Nullable<int> IdDetalle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursosMatriculados> CursosMatriculados { get; set; }
        public virtual DetalleEvaluacion DetalleEvaluacion { get; set; }
    }
}
