//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLoginCAR.DBModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsigCursoRol
    {
        public int IdAsignacion { get; set; }
        public int IdRol { get; set; }
        public int IdCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Role Role { get; set; }
    }
}
