//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLoginCAR.DBModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosMatriculado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursosMatriculado()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int IdCursoMatriculado { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public Nullable<int> IdEvaluacion { get; set; }
        public Nullable<int> IdProgreso { get; set; }
    
        public virtual Evaluacione Evaluacione { get; set; }
        public virtual Progreso Progreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
