//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLoginCAR.DBModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluacione()
        {
            this.CursosMatriculados = new HashSet<CursosMatriculado>();
        }
    
        public int IdEvaluacion { get; set; }
        public Nullable<decimal> ValorObtenido { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public Nullable<int> IdDetalle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursosMatriculado> CursosMatriculados { get; set; }
        public virtual DetalleEvaluacion DetalleEvaluacion { get; set; }
    }
}
