//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLoginCAR.DBModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistroDBEntidades : DbContext
    {
        public RegistroDBEntidades()
            : base("name=RegistroDBEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsigCursoRol> AsigCursoRols { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<CursosMatriculado> CursosMatriculados { get; set; }
        public virtual DbSet<DetalleEvaluacion> DetalleEvaluacions { get; set; }
        public virtual DbSet<Evaluacione> Evaluaciones { get; set; }
        public virtual DbSet<Leccione> Lecciones { get; set; }
        public virtual DbSet<Modulo> Modulos { get; set; }
        public virtual DbSet<Progreso> Progresoes { get; set; }
        public virtual DbSet<Registro> Registroes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoLeccion> TipoLeccions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
