//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLoginCAR.DBModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int IdRegistro { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public string Contrasena { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
